# Generated by Django 3.2.6 on 2022-08-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
