# Generated by Django 3.2.6 on 2022-08-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220816_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth',
            field=models.DateTimeField(default='2000-08-16T12:46:56'),
        ),
    ]
